<#
.SYNOPSIS
Deploys the EMS Web UI to an IIS Web Server.

.DESCRIPTION
This script automates the deployment of the EMS React application to Microsoft Internet Information Services (IIS).
It will:
1. Ensure IIS and the URL Rewrite module are installed.
2. Create an Application Pool (EMS_WebUI_AppPool).
3. Create the IIS Website binding to the specified Port/Hostname.
4. Copy the compiled React build files to the IIS Web Root.
5. Setup a web.config to handle React Router (Client-side routing).

.PARAMETER SourceBuildPath
The path to the 'build' directory generated by 'npm run build'. Default is '.\PowerShellEndPointv2\WebUI\build'

.PARAMETER DestPath
The path where IIS will host the files. Default is 'C:\inetpub\wwwroot\ems'

.PARAMETER WebsiteName
The name of the IIS website. Default is 'EMS_WebUI'

.PARAMETER Port
The port to bind the website to. Default is 80.

.PARAMETER Hostname
The domain name or IP address for the binding. Leave empty for all unassigned.
#>
param(
    [string]$SourceBuildPath = ".\PowerShellEndPointv2\WebUI\build",
    [string]$DestPath = "C:\inetpub\wwwroot\ems",
    [string]$WebsiteName = "EMS_WebUI",
    [int]$Port = 80,
    [string]$Hostname = ""
)

# 1. Check if running as Administrator
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "Please run this script as Administrator."
    Exit
}

# 2. Check IIS Installation
Write-Host "Checking IIS Installation..." -ForegroundColor Cyan
if (-not (Get-WindowsFeature -Name Web-Server).Installed) {
    Write-Host "Installing IIS..." -ForegroundColor Yellow
    Install-WindowsFeature -name Web-Server -IncludeManagementTools
}
Import-Module WebAdministration

# 3. Validate Build Source
if (-not (Test-Path $SourceBuildPath)) {
    Write-Error "Could not find build directory at '$SourceBuildPath'. Please run 'npm run build' first."
    Exit
}

# 4. Prepare Destination
Write-Host "Preparing destination folder at $DestPath..." -ForegroundColor Cyan
if (Test-Path $DestPath) {
    Remove-Item -Path "$DestPath\*" -Recurse -Force -ErrorAction SilentlyContinue
} else {
    New-Item -ItemType Directory -Force -Path $DestPath | Out-Null
}

# 5. Copy Files
Write-Host "Copying compiled React files to IIS directory..." -ForegroundColor Cyan
Copy-Item -Path "$SourceBuildPath\*" -Destination $DestPath -Recurse -Force

# 6. Create web.config for React Client-Side Routing
Write-Host "Generating web.config for React Router..." -ForegroundColor Cyan
$webConfigPath = Join-Path $DestPath "web.config"
$webConfigContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="React Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
    <staticContent>
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
    </staticContent>
  </system.webServer>
</configuration>
"@
Set-Content -Path $webConfigPath -Value $webConfigContent -Encoding UTF8

# 7. Configure IIS Application Pool & Website
Write-Host "Configuring IIS App Pool and Website..." -ForegroundColor Cyan
$appPoolName = "${WebsiteName}_AppPool"

if (-not (Get-WebAppPoolState -Name $appPoolName -ErrorAction SilentlyContinue)) {
    New-WebAppPool -Name $appPoolName | Out-Null
}

# Set App Pool to No Managed Code (since it's just static HTML/JS)
Set-ItemProperty -Path "IIS:\AppPools\$appPoolName" -Name "managedRuntimeVersion" -Value ""

if (Get-Website -Name $WebsiteName -ErrorAction SilentlyContinue) {
    Write-Host "Removing existing IIS Website '$WebsiteName'..." -ForegroundColor Yellow
    Remove-Website -Name $WebsiteName
}

Write-Host "Creating new IIS Website '$WebsiteName' on Port $Port..." -ForegroundColor Green
$bindingInfo = "*:${Port}:${Hostname}"
New-Website -Name $WebsiteName -Port $Port -PhysicalPath $DestPath -ApplicationPool $appPoolName -HostHeader $Hostname | Out-Null

Write-Host "==========================================================" -ForegroundColor Green
Write-Host "DEPLOYMENT SUCCESSFUL!" -ForegroundColor Green
Write-Host "The EMS Web UI is now hosted in IIS."
if ($Hostname) {
    Write-Host "You can access it at: http://$Hostname" -ForegroundColor Cyan
} else {
    Write-Host "You can access it at: http://localhost:$Port" -ForegroundColor Cyan
}
Write-Host "Note: URL Rewrite module MUST be installed in IIS for routing to work." -ForegroundColor Yellow
Write-Host "Download from: https://www.iis.net/downloads/microsoft/url-rewrite" -ForegroundColor Yellow
Write-Host "==========================================================" -ForegroundColor Green
